### ISSUE TITLE
Image disappears on drag/fling

### ISSUE THREAD

**Issue by pitigalari** [igreenwood/loupe#5]
Image does not center automatically if the user drags it out of the screen even if `UseFlingToDismissGesture` is `false`.

![ezgif com-optimize](https://user-images.githubusercontent.com/23375478/79380429-14375980-7f7e-11ea-86ca-f898b07cea9c.gif)

**Comment by igreenwood** [comment]
@roshsoftco 
Thank you so much for using Loupe.
As far as looking the movement of this GIF, it appears that the image has exceeded the threshold (the threshold that determines whether to move the image off-screen or back to its original position) and went off-screen.
In loupe, the `onDismiss()` of the `OnViewTranslateListener` is called when the threshold is exceeded. Please call the code to close the screen (`finish()` for `Activity`) in `onDismiss` function.
FYI, `UseFlingToDismissGesture` is the flag to indicate whether or not to continue animation of the image even after the position of the image exceeds the threshold. If you use `SharedElementsTransition`, please set it to `false` because you don't need the animation after the threshold is exceeded.
If this doesn't solve your problem, please send me the actual code.

**Comment by pitigalari** [comment]
I already know how to `finish()` the `Activity` when the user has moved the image exceeding the threshold. What I want is the image to automatically recenter, up to my understanding it means either the threshold limit must be removed or I'll have recenter it manually in `OnViewTranslateListener().onDismiss()`.

How can I recenter the image without finishing the activity?

**Comment by igreenwood** [comment]
@roshsoftco 
For what purpose do you want to recenter the image after swiping it ?
This library is intended to provide both image scaling and the ability to close the screen by swiping.
If you want to turn off the ability to close the screen by swiping, I think you can achieve your goal by giving `setDragToDismissDistance()` a large enough value.
